### ISSUE TITLE
[Bug] Version ranges only cover latest Minecraft version but should cover all 1.20.x releases

### ISSUE THREAD

**Issue by Qsta981** [glektarssza/minecraft-expanded-gamerules#25]
Much of the playerbase has not updated to 1.20.4 yet, and we would love to be able to use the mod still on 1.20.1 and 1.20.2.

**Comment by glektarssza** [comment]
The mod should be compatible with any 1.20.x version. I think the reason it won't load for any other versions is because of the `mods.toml` file. I will update it shortly.

**Comment by glektarssza** [comment]
Fix in v0.3.1.
